name: Build
on:
  push:
    branches:
      - main
    paths:
      - "app/**"
      - ".github/workflows/build.yaml"
  pull_request:
    paths:
      - "app/**"
      - ".github/workflows/build.yaml"
jobs:
  build:
    name: Build, Scan and Push
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      packages: write
    steps:
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          platforms: linux/arm64
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Build
        uses: docker/build-push-action@v5
        with:
          context: app
          load: true
          tags: ghcr.io/${{ github.actor }}/mopetube:${{ github.sha }},ghcr.io/${{ github.actor }}/mopetube:latest
          platforms: linux/arm64
      - name: Run Trivy
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: "ghcr.io/${{ github.actor }}/mopetube:${{ github.sha }}"
          trivy-config: trivy.yaml
        env:
          TRIVY_PLATFORM: linux/arm64
      - name: Upload Trivy results
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: trivy-results.sarif
      - name: Login to ghcr.io
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Push image
        run: |
          docker push ghcr.io/${{ github.actor }}/mopetube:${{ github.sha }}
          docker push ghcr.io/${{ github.actor }}/mopetube:latest
