name: Build
on:
  push:
    branches:
      - main
    paths:
      - "app/**"
      - ".github/workflows/build.yaml"
  pull_request:
    paths:
      - "app/**"
      - ".github/workflows/build.yaml"
jobs:
  build:
    name: Build, Scan and Push
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      packages: write
    steps:
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          platforms: linux/arm64
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Build a Docker image
        run: docker buildx build --platform linux/arm64 -t mopetube:${{ github.sha }} .
        working-directory: app
      - name: Run Trivy
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: "mopetube:${{ github.sha }}"
          format: "table"
          exit-code: "1"
          ignore-unfixed: true
          severity: "CRITICAL,HIGH"
      - name: Login to ghcr.io
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
        if: ${{ github.event_name == 'push' }}
      - name: Push image to ghcr.io
        run: |
          docker tag mopetube:${{ github.sha }} ghcr.io/${{ github.actor }}/mopetube:${{ github.sha }}
          docker push ghcr.io/${{ github.actor }}/mopetube:${{ github.sha }}
        if: ${{ github.event_name == 'push' }}
